name: Release x86-64-macos

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-13

    steps:
    - uses: actions/checkout@v4
    - name: Install Diesel
      run: cargo install diesel_cli --no-default-features --features sqlite
    - name: Install cargo-bundle
      run: cargo install cargo-bundle
    - name: Build
      run: cargo bundle --profile=release
    - name: Get Version
      run: echo "PKG_VERSION=cargo metadata --format-version=1 --no-deps | jq '.packages[0].version'" >> $GITHUB_ENV
    - uses: actions/upload-artifact@v4
      with:
        name: recipe-manager-${{ env.PKG_VERSION }}-macos-x86-64.app
        path: "target/release/bundle/osx/"

